### PR TITLE
More games to SNES

### PR DESCRIPTION
**Pull request by webysther**
image

### CODE REVIEW

**Comment by webysther** [comment]
For some reason upload stop working and new data added don't show the checksum anymore, maybe because the gateway stop working? Anyway, here the logo and video for Mega Man X (Europe) if you can upload from you side:

Mega Man X (Europe)

https://github.com/linuxserver/emulatorjs/assets/750007/0da775c6-df70-4301-b059-b75c6f2a6fe1

**Comment by webysther** [comment]
https://github.com/linuxserver/emulatorjs/assets/750007/33ba164e-e4a8-4944-ada0-bc8cfcb5d0dd

**Comment by webysther** [comment]
Video PSX: Alone in the Dark - One-Eyed Jack's Revenge (USA)


https://github.com/linuxserver/emulatorjs/assets/750007/4d01b3b6-0d42-46ed-adb9-6bc4041aa190

**Comment by thelamer** [comment]
I fixed the ipfs interaction not working in the docker image, please pull that update you can use the web interface again to customize assets. 

As far as adding these port 4001 (IPFS p2p) on your local container needs to be exposed to the internet. Once that is setup basically a node out there needs to request it so to confirm it is functional you hit a public gateway by the CID in the metadata IE: 

https://gateway.pinata.cloud/ipfs/QmTLXWbkQU1o4exSkQqQvrKQAWULdQvaza4TJ4wFfbzrYU

Once you have confirmed a public gateway can show at least one of your files I have no problem pinging them to get the rest. You just need to ensure you are able to share. IE from the DK PR: 

https://gateway.pinata.cloud/ipfs/QmdKfS2wHk5KiBMiGfDEhLQt1kMBkWVEoLz24RmPTXaQza

I pinged this a bunch from pub gateways and local nodes but I am unable to get the file. 

I know it is a pain but once it is setup properly it streamlines adding stuff and future proofs the application with a p2p network.

**Comment by webysther** [comment]
> I fixed the ipfs interaction not working in the docker image, please pull that update you can use the web interface again to customize assets.
> 
> As far as adding these port 4001 (IPFS p2p) on your local container needs to be exposed to the internet. Once that is setup basically a node out there needs to request it so to confirm it is functional you hit a public gateway by the CID in the metadata IE:
> 
> https://gateway.pinata.cloud/ipfs/QmTLXWbkQU1o4exSkQqQvrKQAWULdQvaza4TJ4wFfbzrYU
> 
> Once you have confirmed a public gateway can show at least one of your files I have no problem pinging them to get the rest. You just need to ensure you are able to share. IE from the DK PR:
> 
> https://gateway.pinata.cloud/ipfs/QmdKfS2wHk5KiBMiGfDEhLQt1kMBkWVEoLz24RmPTXaQza
> 
> I pinged this a bunch from pub gateways and local nodes but I am unable to get the file.
> 
> I know it is a pain but once it is setup properly it streamlines adding stuff and future proofs the application with a p2p network.

Hi, man I tried to read you reply multiple times about the update but don't get it, maybe I'm stupid, you mean the version 1.8.1?

The port is open and forward without no restriction, is possible to you check if ok? 79.98.43.212:4001

**Comment by thelamer** [comment]
This commit allows you to upload media from the web interface again in the web interface just need to update the container.
https://github.com/linuxserver/docker-emulatorjs/commit/21b8d8eda6be8daffe8f99f68e41155a2a591674

You might need to reupload the media as it was broken before.

**Comment by webysther** [comment]
> https://gateway.pinata.cloud/ipfs/QmdKfS2wHk5KiBMiGfDEhLQt1kMBkWVEoLz24RmPTXaQza

Done! For new video and images I need to download from my folder and upload again using the UI, right?

**Comment by thelamer** [comment]
Yeah unfortunately, there are cli methods using ipfs add, but honestly we might end up breaking more things than it's worth.
With one confirmed you don't have to ping public gateways anymore if you don't want to I have scripts for that and I can get them over to the primary seed server. 
Thanks for taking the time to go through this stuff, I have metadata updates time slotted for tomorrow and will cut a new release to get this out there.

**Comment by webysther** [comment]
> Yeah unfortunately, there are cli methods using ipfs add, but honestly we might end up breaking more things than it's worth. With one confirmed you don't have to ping public gateways anymore if you don't want to I have scripts for that and I can get them over to the primary seed server. Thanks for taking the time to go through this stuff, I have metadata updates time slotted for tomorrow and will cut a new release to get this out there.

No problem, I have a nephew who lives in Brazil and I moved to Italy almost 2 years ago, I'm doing this so I can have fun with him, in the future I want to see if I can make netplay work or something like that, he's having a lot of fun and it makes me very happy. Thanks a lot!

**Pull request merged**
