### PR TITLE
Remove code that prevents cue from loading

### PR DESCRIPTION
**Pull request by rrgeorge**
This block seems to prevent the cue file from loading with the logic at line 185

### CODE REVIEW

**Comment by thelamer** [comment]
Bin/Cue in general is not great code. It will only work with single Bin/Cue files.
What happens is that the rom scanner on the backend actually ignores the cue file when loading in games: 
 https://github.com/linuxserver/emulatorjs/blob/master/has_files.sh#L149

Then when loading the rom in libretro.js because it is a bin file that is being passed it renames the rom to launch that is executed here on the Main emscripten call: 
https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/libretro.js#L63
All the emulators that I tried load the cue file not the bin file to actually launch a game. 

In general optimally you would actually parse the cue files from the js and download everything listed in it. But standards for cue files are not super reliable and would be hacky regexp stuff. 

What is your setup that you are testing (the json config and platform)?

**Comment by rrgeorge** [comment]
With that section in place, it only downloads the bin file, and the emulator says the ROM exceeds the maximum size.
I removed that section, and it downloaded both bin/cue files and loaded in the emulator successfully.

**Comment by rrgeorge** [comment]
> What is your setup that you are testing (the json config and platform)?

I'm playing on an iPad Pro with a gamepad. The bin/cue files I'm testing are SegaCD roms.

**Comment by thelamer** [comment]
I see what you are saying, old logic mixed with new, it was writing the bin file as a cue. I know stuff like PSX wants the cue file to load so the renaming of what to load is still needed. This works I just tested it with chdman extracted stuff(single bin/cue)
Again though I would recommend  compressing down to chd for CD based retroarch stuff.

**Comment by rrgeorge** [comment]
> Again though I would recommend compressing down to chd for CD based retroarch stuff.

Oh yeah this is much better. Thanks for the tip.

**Pull request merged**
