### PR TITLE
Needs polyfill for Array.at() in Safari

### PR DESCRIPTION
**Pull request by rrgeorge**
Array.at() is new and not fully supported across browsers. This polyfill should resolve that.

### CODE REVIEW

**Comment by thelamer** [comment]
I tested the file browser in webkit, is something specifically not working ?

**Comment by rrgeorge** [comment]
It doesn’t load any in safari without the polyfill. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at), `Array.at()` is still experimental and only available in Safari Technology Preview.

**Comment by thelamer** [comment]
What about just going back to slice, I am not married to at? 
I hate that you need apple gear to test this stuff properly, my OSX vm only lets me go so far without an audio device.

**Comment by rrgeorge** [comment]
Thats probably fine. The issue with `at` is just because its new and hasn't been implemented in the current production Safari. It was only just implemented in Chrome 92, which was released in July.

**Comment by rrgeorge** [comment]
Sorry. I think slice returns an array, so you need to do `.slice(-1)[0]`

**Comment by rrgeorge** [comment]
Nevermind, it seems to work fine.

**Comment by thelamer** [comment]
Yes it does, but it is a mystery as to why, I'll stick with your recommendation. I'll cut a release too as this is busted. 
Thanks again.

**Pull request merged**
